# Generated by Django 6.0.4 on 2026-04-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('company_name', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('daily_return', models.FloatField(blank=True, null=True)),
                ('ma_7', models.FloatField(blank=True, null=True)),
                ('volatility', models.FloatField(blank=True, null=True)),
                ('week_52_high', models.FloatField(blank=True, null=True)),
                ('week_52_low', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['symbol', 'date'],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
